--- 
components: 
  schemas: 
    AeroAllergenObserved: 
      $ref: "https://smart-data-models.github.io/dataModel.Environment/AeroAllergenObserved/model.yaml#/AeroAllergenObserved"
info: 
  description: |
    This data model has been developed based on
    [GSMA](https://www.gsma.com/iot/iot-big-data/). Aero allergens strictly depends
    on the geographical location. Common Aero allergens in Europe may be quite
    different from the ones in US due to the different biological species. A list of
    commonly used aero allergens in Europe can be found on
    [polleninfo.org](https://www.polleninfo.org/en/allergy/profiles/) a web site
    maintained by the European Aeroallergen Network. A World Health Organization
    (WHO) Allergen Nomenclature (covering not only aero transported allergens) is
    available at [http://www.allergen.org](http://www.allergen.org).
  title: AeroAllergenObserved
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - AeroAllergenObserved
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Environment/AeroAllergenObserved/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Environment/AeroAllergenObserved/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
